# Number of days of inactivity before an issue becomes stale
daysUntilStale: 10
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 2
# Issues with these labels will never be considered stale
exemptLabels:
  - pinned
  - security
# Label to use when marking an issue as stale
staleLabel: wontfix
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  Thank you for your pull request. The GHTorrent project stopped
  offering shell access to data services in Jun 2019. This pull request
  will be closed. If you request access to personal data, please note that
  GDPR does allow GHTorrent to distribute those since May 2018.

  Please ping @gousiosg for other requests.
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false
